## <u> Use only those concepts which have been taught till now </u>

# <b> Problem 1: Import Pandas and Numpy in the notebook </b>

In [1]:
# Import statements
import pandas as pd
import numpy as np

# <b> Problem 2 : Load the automobile_data.csv kept in the shared folder

In [4]:
# Mount your drive and read the csv file. Make sure you are using the correct file path

df = pd.read_csv(r"C:\Users\DELL\Downloads\05-04 Materials\automobile_data.csv")

# <b> Problem 3 : Do a basic inspection and print the first and last 15 rows of your dataframe

In [5]:
# Your code here
df.head(15)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.4,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.4,8.0,115,5500,18,22,17450
5,2,?,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.4,8.5,110,5500,19,25,15250
6,1,158,audi,gas,std,four,sedan,fwd,front,105.8,...,136,mpfi,3.19,3.4,8.5,110,5500,19,25,17710
7,1,?,audi,gas,std,four,wagon,fwd,front,105.8,...,136,mpfi,3.19,3.4,8.5,110,5500,19,25,18920
8,1,158,audi,gas,turbo,four,sedan,fwd,front,105.8,...,131,mpfi,3.13,3.4,8.3,140,5500,17,20,23875
9,0,?,audi,gas,turbo,two,hatchback,4wd,front,99.5,...,131,mpfi,3.13,3.4,7.0,160,5500,16,22,?
10,2,192,bmw,gas,std,two,sedan,rwd,front,101.2,...,108,mpfi,3.5,2.8,8.8,101,5800,23,29,16430
11,0,192,bmw,gas,std,four,sedan,rwd,front,101.2,...,108,mpfi,3.5,2.8,8.8,101,5800,23,29,16925
12,0,188,bmw,gas,std,two,sedan,rwd,front,101.2,...,164,mpfi,3.31,3.19,9.0,121,4250,21,28,20970
13,0,188,bmw,gas,std,four,sedan,rwd,front,101.2,...,164,mpfi,3.31,3.19,9.0,121,4250,21,28,21105
14,1,?,bmw,gas,std,four,sedan,rwd,front,103.5,...,164,mpfi,3.31,3.19,9.0,121,4250,20,25,24565

In [6]:
df.tail(15)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
190,3,256,volkswagen,gas,std,two,hatchback,fwd,front,94.5,...,109,mpfi,3.19,3.4,8.5,90,5500,24,29,9980
191,0,?,volkswagen,gas,std,four,sedan,fwd,front,100.4,...,136,mpfi,3.19,3.4,8.5,110,5500,19,24,13295
192,0,?,volkswagen,diesel,turbo,four,sedan,fwd,front,100.4,...,97,idi,3.01,3.4,23.0,68,4500,33,38,13845
193,0,?,volkswagen,gas,std,four,wagon,fwd,front,100.4,...,109,mpfi,3.19,3.4,9.0,88,5500,25,31,12290
194,-2,103,volvo,gas,std,four,sedan,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,12940
195,-1,74,volvo,gas,std,four,wagon,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,13415
196,-2,103,volvo,gas,std,four,sedan,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114,5400,24,28,15985
197,-1,74,volvo,gas,std,four,wagon,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114,5400,24,28,16515
198,-2,103,volvo,gas,turbo,four,sedan,rwd,front,104.3,...,130,mpfi,3.62,3.15,7.5,162,5100,17,22,18420
199,-1,74,volvo,gas,turbo,four,wagon,rwd,front,104.3,...,130,mpfi,3.62,3.15,7.5,162,5100,17,22,18950
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.4,23.0,106,4800,26,27,22470
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

# <b>Problem 4 : You need to clean the data a little bit now. Replace all column values with the values <code>?</code> and <code>n.a</code> with <code>NaN</code>

In [7]:
# Your code here

df.replace(['?', 'n.a'], np.nan, inplace=True)

# <b>Problem 5 : Print the company name which manufactured the most expensive car. Also print the price of the most expensive car

In [9]:
# Your code here

max_price_row = df.loc[df['price'].idxmax()]

print("Company:", max_price_row['make'])
print("Price:", max_price_row['price'])

Company: mercedes-benz
Price: 45400.0

# <b>Problem 6 : Calculate maximum horsepowers for each company. </b>

In [10]:
# Your code here

max_hp_by_make = df.groupby('make')['horsepower'].max()

print(max_hp_by_make)

make
alfa-romero      154
audi             160
bmw              182
chevrolet         70
dodge             88
honda             86
isuzu             90
jaguar           262
mazda             84
mercedes-benz    184
mercury          175
mitsubishi        88
nissan            97
peugot            97
plymouth          88
porsche          288
renault          NaN
saab             160
subaru            94
toyota            92
volkswagen        90
volvo            162
Name: horsepower, dtype: object

# <b> Problem 7 : Print the total number of cars manufactured by each company

In [12]:
# Your code here
car_count_by_company = df['make'].value_counts()
print(car_count_by_company)

make
toyota           32
nissan           18
mazda            17
mitsubishi       13
honda            13
subaru           12
volkswagen       12
volvo            11
peugot           11
dodge             9
mercedes-benz     8
bmw               8
audi              7
plymouth          7
saab              6
porsche           5
isuzu             4
alfa-romero       3
chevrolet         3
jaguar            3
renault           2
mercury           1
Name: count, dtype: int64

# <b> Problem 8 : Create a new column for the updated price. This updated price will be calculated on top of the given price - if the engine is in front, price will be same else if the engine is in rear, price will be doubled </b>

In [13]:
# Your code here. Use apply and lambda

df['updated-price'] = df.apply(
    lambda row: row['price'] * 2 if row['engine-location'] == 'rear' else row['price'],
    axis=1
)
print(df.head(10))

   symboling normalized-losses         make fuel-type aspiration num-of-doors  \
0          3               NaN  alfa-romero       gas        std          two
1          3               NaN  alfa-romero       gas        std          two
2          1               NaN  alfa-romero       gas        std          two
3          2               164         audi       gas        std         four
4          2               164         audi       gas        std         four
5          2               NaN         audi       gas        std          two
6          1               158         audi       gas        std         four
7          1               NaN         audi       gas        std         four
8          1               158         audi       gas      turbo         four
9          0               NaN         audi       gas      turbo          two

    body-style drive-wheels engine-location  wheel-base  ...  fuel-system  \
0  convertible          rwd           front        88.6  ...         mpfi
1  convertible          rwd           front        88.6  ...         mpfi
2    hatchback          rwd           front        94.5  ...         mpfi
3        sedan          fwd           front        99.8  ...         mpfi
4        sedan          4wd           front        99.4  ...         mpfi
5        sedan          fwd           front        99.8  ...         mpfi
6        sedan          fwd           front       105.8  ...         mpfi
7        wagon          fwd           front       105.8  ...         mpfi
8        sedan          fwd           front       105.8  ...         mpfi
9    hatchback          4wd           front        99.5  ...         mpfi

   bore  stroke  compression-ratio horsepower peak-rpm  city-mpg highway-mpg  \
0  3.47    2.68                9.0        111     5000        21          27
1  3.47    2.68                9.0        111     5000        21          27
2  2.68    3.47                9.0        154     5000        19          26
3  3.19     3.4               10.0        102     5500        24          30
4  3.19     3.4                8.0        115     5500        18          22
5  3.19     3.4                8.5        110     5500        19          25
6  3.19     3.4                8.5        110     5500        19          25
7  3.19     3.4                8.5        110     5500        19          25
8  3.13     3.4                8.3        140     5500        17          20
9  3.13     3.4                7.0        160     5500        16          22

     price updated-price
0  13495.0       13495.0
1  16500.0       16500.0
2  16500.0       16500.0
3  13950.0       13950.0
4  17450.0       17450.0
5  15250.0       15250.0
6  17710.0       17710.0
7  18920.0       18920.0
8  23875.0       23875.0
9      NaN           NaN

[10 rows x 27 columns]

# <b>Problem 9 : Sort the dataframe by car and price columns

In [14]:
# Your code here
df_sorted = df.sort_values(by=['make', 'price'])

print(df_sorted[['make', 'price']].head(10))

          make    price
0  alfa-romero  13495.0
1  alfa-romero  16500.0
2  alfa-romero  16500.0
3         audi  13950.0
5         audi  15250.0
4         audi  17450.0
6         audi  17710.0
7         audi  18920.0
8         audi  23875.0
9         audi      NaN

# <b> Problem 10 : Create a new column which stores the number of doors in a car as integers.

In [15]:
# Your code here. Use apply
df['num-of-doors-int'] = df['num-of-doors'].apply(
    lambda x: 2 if x == 'two' else 
              3 if x == 'three' else 
              4 if x == 'four' else 
              5 if x == 'five' else 
              6 if x == 'six' else np.nan
)

print(df[['num-of-doors', 'num-of-doors-int']].head(10))

  num-of-doors  num-of-doors-int
0          two               2.0
1          two               2.0
2          two               2.0
3         four               4.0
4         four               4.0
5          two               2.0
6         four               4.0
7         four               4.0
8         four               4.0
9          two               2.0

# <b>Problem 11 : Concatenate the two data frames given below firstly row wise and secondly column wise.</b>

<code>GermanCars = {'Company': ['Ford', 'Mercedes', 'BMV', 'Audi'], 'Price': [23845, 171995, 135925 , 71400]}</code>

<code>japaneseCars = {'Company': ['Toyota', 'Honda', 'Nissan', 'Mitsubishi '], 'Price': [29995, 23600, 61500 , 58900]}</code>

In [16]:
# Your code here

GermanCars = {
    'Company': ['Ford', 'Mercedes', 'BMV', 'Audi'],
    'Price': [23845, 171995, 135925, 71400]
}

japaneseCars = {
    'Company': ['Toyota', 'Honda', 'Nissan', 'Mitsubishi '],
    'Price': [29995, 23600, 61500, 58900]
}

df_german = pd.DataFrame(GermanCars)
df_japanese = pd.DataFrame(japaneseCars)

In [17]:
row_wise = pd.concat([df_german, df_japanese], ignore_index=True)
print("Row-wise concatenation:\n", row_wise)

Row-wise concatenation:
        Company   Price
0         Ford   23845
1     Mercedes  171995
2          BMV  135925
3         Audi   71400
4       Toyota   29995
5        Honda   23600
6       Nissan   61500
7  Mitsubishi    58900

In [18]:
column_wise = pd.concat([df_german, df_japanese], axis=1)
print("\nColumn-wise concatenation:\n", column_wise)

Column-wise concatenation:
     Company   Price      Company  Price
0      Ford   23845       Toyota  29995
1  Mercedes  171995        Honda  23600
2       BMV  135925       Nissan  61500
3      Audi   71400  Mitsubishi   58900